"""empty message

Revision ID: 234106888d73
Revises: 
Create Date: 2024-06-12 23:47:28.752890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '234106888d73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicule')
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solde', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('solde')

    op.create_table('vehicule',
    sa.Column('_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('numero_immatriculation', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('marque', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('modele', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('couleur', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('annee', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photos', mysql.TEXT(), nullable=True),
    sa.Column('propietaire', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['propietaire'], ['utilisateur.id'], name='vehicule_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
